### ISSUE TITLE
Different color on quick links

### ISSUE THREAD

**Issue by gabbsmo** [n8design/htwoo#151] opened 2024-08-21 13:50 UTC
**Describe the bug**
While testing the different quick links styles I noticed that if you changed the top level `<div>` tag to `<a>` the text color would change in the large variante, but not for the compact ones. Since the compact variants have an explicit `color` set it seems like this was forgotten about for the large variants.

**To Reproduce**
1. See [Compact Quick Links in Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=organism-quick-links-compact-grid)
2. Change a `<div>` to `<a>` for a `.hoo-qlcompact`
3. Notice text color is same
4. See [Quick Links Outline Grid in Pattern Lab](https://lab.n8d.studio/htwoo/htwoo-core/?p=organism-quick-links-button-outline-grid) 
5. Change a `<div>` to `<a>` for a `.hoo-qlbtn`
6. Notice text color is changed to the regular text link color

**Expected behavior**
Button text should have text color, not link color. Not sure about `:hover`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 127

**Additional context**
Entierly possible that I got this the wrong way around. Could not find a reference in Fluent UI but SharePoint is using text color at least. Also SharePoint use bold text, but that is perhaps something that is best left for applications to deside or a separate issue?

**Comment by gabbsmo** [comment] 2024-08-28 07:55
Another idea, would it be possible to allow for developers to choose whether the quick link container is the `<a>` or a child element, for example in the case there are multiple links in one box?

**Comment by StfBauer** [comment] 2024-11-03 16:10
The issue is a bit different. There should be a wrapping link around the items. Classname: hoo-qllink.
The div on the other hand should be a `<article>`.

**Comment by StfBauer** [comment] 2024-11-08 09:10
Should be fixed.

**Closed by StfBauer** 2024-11-08 09:10 UTC
